## DataSet(AI Jobs & Salaries 2025–26)
job_category: The broader field or domain of the job within AI and data science.

experience_level: The required experience level for the position (Entry, Mid, Senior, Lead).

years_of_experience: The number of years of professional experience required for the job.

education_required: The minimum educational qualification required for the role.

annual_salary_usd: The estimated average annual salary for the position in USD.

salary_min_usd: The minimum salary offered for the job role.

salary_max_usd: The maximum salary offered for the job role.

city: The city where the job position is located.

country: The country where the job is offered.

remote_work: Indicates whether the job allows remote work or requires on-site presence.

company_size: The size category of the company offering the job (Small, Medium, Large).

industry: The industry sector in which the company operates.

required_skills: The key technical skills required for the job role.

ai_salary_premium_pct: The percentage increase in salary attributed to AI-related expertise.

demand_score: A score representing the market demand level for the job role.

demand_growth_yoy_pct: The year-over-year percentage growth in demand for the role.

benefits_score_10: A rating from 1 to 10 reflecting the quality of job benefits offered.

posting_year: The year when the job posting was published.

posting_month: The month when the job posting was published.

is_senior: A binary indicator showing whether the role is senior-level (1) or not (0).

is_remote_friendly: Indicates whether the company supports remote-friendly work policies.

is_llm_role: Indicates whether the job role involves Large Language Model technologies.

salary_tier: A categorical classification of salary levels (Entry, Mid, Upper-Mid, Senior, Elite

## Library

In [1]:
! pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 4.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from catboost import CatBoostClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, f1_score


#

In [3]:
## Upload Dataset
from google.colab import files

uploaded = files.upload()  # Opens a file picker in your browser

Saving ai_jobs_market_2025_2026.csv to ai_jobs_market_2025_2026.csv

In [4]:
## Read Dataset
data=pd.read_csv("ai_jobs_market_2025_2026.csv")
data.head(1)

,job_id,job_title,job_category,experience_level,years_of_experience,education_required,annual_salary_usd,salary_min_usd,salary_max_usd,city,...,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role,salary_tier
0,AIJOB0001,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,239000,155000,290000,Boston,...,13.1,96,16.9,6.8,2026,3,1,0,1,Senior ($200-300k)

## Explotary Data

In [5]:
## information _data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 1500 non-null   object
 1   job_title              1500 non-null   object
 2   job_category           1500 non-null   object
 3   experience_level       1500 non-null   object
 4   years_of_experience    1500 non-null   int64
 5   education_required     1500 non-null   object
 6   annual_salary_usd      1500 non-null   int64
 7   salary_min_usd         1500 non-null   int64
 8   salary_max_usd         1500 non-null   int64
 9   city                   1500 non-null   object
 10  country                1500 non-null   object
 11  remote_work            1500 non-null   object
 12  company_size           1500 non-null   object
 13  industry               1500 non-null   object
 14  required_skills        1500 non-null   object
 15  ai_salary_premium_pct  1500 non-null   float64
 16  demand_score           1500 non-null   int64
 17  demand_growth_yoy_pct  1500 non-null   float64
 18  benefits_score_10      1500 non-null   float64
 19  posting_year           1500 non-null   int64
 20  posting_month          1500 non-null   int64
 21  is_senior              1500 non-null   int64
 22  is_remote_friendly     1500 non-null   int64
 23  is_llm_role            1500 non-null   int64
 24  salary_tier            1500 non-null   object
dtypes: float64(3), int64(10), object(12)
memory usage: 293.1+ KB

In [6]:
data.shape

(1500, 25)

In [7]:
data.describe()

,years_of_experience,annual_salary_usd,salary_min_usd,salary_max_usd,ai_salary_premium_pct,demand_score,demand_growth_yoy_pct,benefits_score_10,posting_year,posting_month,is_senior,is_remote_friendly,is_llm_role
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,6.216000,194892.000000,135448.666667,257537.333333,10.858200,87.523333,31.116333,7.897333,2025.584000,3.968000,0.496667,0.754000,0.218000
std,2.675216,66506.822013,24448.950878,39852.822207,4.029742,8.026315,22.046343,1.102846,0.493058,3.270388,0.500156,0.430822,0.413025
min,1.000000,90000.000000,90000.000000,180000.000000,3.000000,68.000000,5.000000,6.000000,2025.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,144750.000000,120000.000000,218000.000000,8.200000,82.000000,15.375000,6.900000,2025.000000,2.000000,0.000000,1.000000,0.000000
50%,6.000000,180000.000000,140000.000000,270000.000000,10.500000,89.000000,23.400000,7.900000,2026.000000,3.000000,0.000000,1.000000,0.000000
75%,8.000000,236250.000000,155000.000000,290000.000000,14.200000,95.000000,42.700000,8.900000,2026.000000,5.000000,1.000000,1.000000,0.000000
max,15.000000,384000.000000,180000.000000,320000.000000,18.000000,98.000000,87.800000,9.800000,2026.000000,12.000000,1.000000,1.000000,1.000000

In [8]:
data.shape

(1500, 25)

In [9]:
## explore null
data.isnull().sum().max()

0

In [10]:
## Duplication
data.duplicated().sum()

np.int64(0)

In [11]:
## Categorical_column IN Data
Categorical_column=data.select_dtypes(include=['object']).columns
Categorical_column

Index(['job_id', 'job_title', 'job_category', 'experience_level',
       'education_required', 'city', 'country', 'remote_work', 'company_size',
       'industry', 'required_skills', 'salary_tier'],
      dtype='object')

In [12]:
## Numerical_column IN Data
Numerical_column=data.select_dtypes(include=['int64','float64']).columns
Numerical_column

Index(['years_of_experience', 'annual_salary_usd', 'salary_min_usd',
       'salary_max_usd', 'ai_salary_premium_pct', 'demand_score',
       'demand_growth_yoy_pct', 'benefits_score_10', 'posting_year',
       'posting_month', 'is_senior', 'is_remote_friendly', 'is_llm_role'],
      dtype='object')

 ## Preprocessing for ML

In [13]:
## Drop Columns
df= data.drop(columns=["job_id",  'annual_salary_usd','salary_min_usd','salary_max_usd','posting_year','posting_month','is_remote_friendly','is_senior','ai_salary_premium_pct','demand_score'])

In [14]:
df.head(1)

,job_title,job_category,experience_level,years_of_experience,education_required,city,country,remote_work,company_size,industry,required_skills,demand_growth_yoy_pct,benefits_score_10,is_llm_role,salary_tier
0,AI Agent Developer,AI Engineering,Senior (6-9 yrs),7,Master's,Boston,USA,On-site,Startup (1-50),Finance,APIs|Planning Systems|Python|Cloud|SQL|Leadership,16.9,6.8,1,Senior ($200-300k)

## Feature Engineering

In [15]:
### split  each skills to features and encoding each skill to 0 ,1
skills_encoded = df['required_skills'].str.get_dummies(sep='|')

In [16]:
skills_encoded .shape

(1500, 93)

In [17]:
data=pd.concat([data,skills_encoded],axis=1)
data.drop(columns=['required_skills'],inplace=True)

In [18]:
### splite for experience_level about year
df['experience_level'] = df['experience_level'].str.replace(')', '', regex=False).str.split(r' \(').str[0]

In [19]:
### splite for company_size about number_employeers
df['company_size'] = df['company_size'].str.replace(')', '', regex=False).str.split(r' \(').str[0]

### Target Columns

####  benefits_score_10

In [20]:
###   benefits_score_10 to Level Low / Medium / High
df['benefits_score_10']=pd.cut(df['benefits_score_10'],bins=[0,4,7,10],labels=['Low','Medium','High'])

In [21]:
## category of benefits_score_10
df['benefits_score_10'].value_counts()

benefits_score_10
High      1078
Medium     422
Low          0
Name: count, dtype: int64


####  demand_growth_yoy_pc

In [22]:
## Divide demand_growth_yoy_pct to Level Declining / Stable / Growing
df['demand_growth_yoy_pct']=pd.cut(df['demand_growth_yoy_pct'],bins=[0,33,66,100],labels=['Declining','Stable','Growing'])

In [23]:
## category of demand_growth_yoy_pct
df['demand_growth_yoy_pct'].value_counts()

demand_growth_yoy_pct
Declining    1048
Stable        265
Growing       187
Name: count, dtype: int64

### category of salary_tier

In [24]:
## category of salary_tier
df['salary_tier'].value_counts()

salary_tier
Senior ($200-300k)       467
Upper-Mid ($150-200k)    430
Mid ($100-150k)          396
Elite (>$300k)           140
Entry (<$100k)            67
Name: count, dtype: int64

### Divide data to Features and Target Columns

In [25]:
### split data to features and target
x=df.drop(columns=['salary_tier','benefits_score_10','demand_growth_yoy_pct'])
y=df[['salary_tier','benefits_score_10','demand_growth_yoy_pct']]

In [26]:
### category_features
Categorical_column_features=list(x.select_dtypes(include=['object','category']).columns)
Categorical_column_features

['job_title',
 'job_category',
 'experience_level',
 'education_required',
 'city',
 'country',
 'remote_work',
 'company_size',
 'industry',
 'required_skills']

###  Split Data  To Training Dataset And Testing Dataset

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

### StratifiedKFold

In [ ]:
#pip install git+https://github.com/trent-b/iterative-stratification.git

In [236]:
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold

mskf = MultilabelStratifiedKFold(n_splits=12, shuffle=True, random_state=42)

for train_index, val_index in mskf.split(x, y):
    x_train, x_val = x.iloc[train_index], x.iloc[val_index]
    y_train, y_val = y.iloc[train_index], y.iloc[val_index]

    # Train multi-output model

## Models

#### CatBoost

In [264]:
# Multi-Output Classifier
model = MultiOutputClassifier(
    CatBoostClassifier(
        iterations=300,
        depth=6,
        learning_rate=0.6,
        l2_leaf_reg=0.01,
        loss_function='MultiClass',
        verbose=100,
        early_stopping_rounds=10
    )
)

In [265]:
model.fit(x_train, y_train,  cat_features=Categorical_column_features)

0:	learn: 1.0837567	total: 93.1ms	remaining: 27.8s
100:	learn: 0.0211121	total: 7.85s	remaining: 15.5s
200:	learn: 0.0017370	total: 15.2s	remaining: 7.49s
299:	learn: 0.0003917	total: 23.5s	remaining: 0us
0:	learn: 0.6054060	total: 2.67ms	remaining: 800ms
100:	learn: 0.0770864	total: 1.24s	remaining: 2.45s
200:	learn: 0.0102097	total: 2.5s	remaining: 1.23s
299:	learn: 0.0022136	total: 3.76s	remaining: 0us
0:	learn: 0.6095127	total: 4.98ms	remaining: 1.49s
100:	learn: 0.0108701	total: 2.67s	remaining: 5.27s
200:	learn: 0.0007243	total: 5.41s	remaining: 2.66s
299:	learn: 0.0001935	total: 9.3s	remaining: 0us

MultiOutputClassifier(estimator=CatBoostClassifier(depth=6, early_stopping_rounds=10, iterations=300, l2_leaf_reg=0.01, learning_rate=0.6, loss_function='MultiClass', verbose=100))

### Acurracy StratifiedKFold vaildation

In [266]:
from sklearn.metrics import accuracy_score

y_pred6 = model.predict(x_val).squeeze()

In [267]:

results = {}
for i, col in enumerate(y_val.columns):
    results[col] = accuracy_score(y_val.iloc[:, i], y_pred6[:, i])
    print(col,":",results[col])

salary_tier : 0.832
benefits_score_10 : 0.568
demand_growth_yoy_pct : 0.656

In [268]:
## predict_test
y_pred_train=model.predict(x_train).squeeze()
y_pred_test=model.predict(x_test).squeeze()

In [269]:
print(accuracy_score(y_train.values.flatten(),y_pred_train.flatten()))

0.8387878787878787

### Accuracy_Testing

In [270]:
## predict_test
acc1 = accuracy_score(
    y_test.values.flatten(),  # keep this if y_test is a DataFrame
    y_pred_test.flatten()          # remove .values here
)
print("Flattened Accuracy:", acc1)

Flattened Accuracy: 0.8429629629629629

## Accuracy_Training

In [271]:
from sklearn.metrics import accuracy_score

y_pred_train = y_pred_train.squeeze()
results = {}

for i, col in enumerate(y_train.columns):
    results[col] = accuracy_score(y_train.iloc[:, i], y_pred_train[:, i])
    print(col,":",results[col])

salary_tier : 0.9003636363636364
benefits_score_10 : 0.7709090909090909
demand_growth_yoy_pct : 0.8450909090909091

## Acurracy For Each column Target

In [272]:
from sklearn.metrics import accuracy_score

y_pred = y_pred_test.squeeze()
results = {}

for i, col in enumerate(y_test.columns):
    results[col] = accuracy_score(y_test.iloc[:, i], y_pred[:, i])
    print(col,":",results[col])

salary_tier : 0.9044444444444445
benefits_score_10 : 0.7644444444444445
demand_growth_yoy_pct : 0.86

### Bagging